- injectproxy/routes.go
After writing with http.Error to the http.ResponseWriter we need to return.
/cc @s-urbaniak
> Return after http.Error

- Dockerfile
- Makefile
- examples/deployment.yaml
I created the docker repo on quay and pushed the current state of this repo to it, so we can move forward with testing. Once this is merged I would tag the v0.1.0 tag on this repo and branch a `release-0.1` branch.
@metalmatze @s-urbaniak
> Update docker repo

- injectproxy/routes_test.go
Adding some tests for existing code before extending support for rules and alerts.
> injectproxy: add unit tests

- README.md
- go.mod
- injectproxy/routes.go
- injectproxy/routes_test.go
- injectproxy/rules.go
- injectproxy/rules_test.go
- main.go
This change revisits heavily `injectproxy.routes` because prom-label-proxy needs to filter rules from the upstream's response rather than hacking/injecting query parameters in the incoming request. Hopefully the unit tests should make sure that there's no regression.
> Add support for /api/v1/rules

- main.go
Setting the -label to an empty value is a mistake as well as using an
upstream URL that's not http or https.
> Check label and upstream URL flags

- .circleci/config.yml
DockerHub announced that as of Nov 1 2020, the number of downloads for
unauthenticated users will be limited. quay.io has no such restrictions
(for now) and there's little incentive for us to host the container
images on 2 platforms.
Closes #41
> Don't push images to DockerHub

- Makefile
- README.md
We accidentally pushed our image to https://quay.io/repository/prometheuscommunity/bind-exporter :disappointed:
> Fix container image name in Makefile

- .circleci/config.yml
Environment variables defined in the organization's context take
[precedence](https://circleci.com/docs/2.0/env-vars/#order-of-precedence) over variables defined in the project. We use Quay
credentials (QUAY_LOGIN/QUAY_PASSWORD) that are scoped to the project
so we shouldn't pull the variables from the context.
> .circleci/config.yml: don't use org context

- CHANGELOG.md
- README.md
- injectproxy/routes.go
- injectproxy/routes_test.go
- main.go
Went ahead and implemented all APIs (: Disabled labels behind flag as there is only WIP PRs present right now.
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
> Added support for metadata APIs.

- injectproxy/routes.go
- injectproxy/routes_test.go
- injectproxy/silences_test.go
Currently, the prom-label-proxy does not support proxying requests that
are sent via the HTTP POST method, whereas the Prometheus HTTP API
accepts query requests via both GET and POST.
This commit adds support for proxying queries via HTTP POST.
Note: these are the important cases to consider:
* POST requests can send the query via the URL query string;
* POST requests can send the query via the POST body;
* POST requests can send two queries, one in the POST body and another
in the URL query string; the Prometheus API's implementation implicitly
choses the query from the POST body, but relying on this implicit
behavior could lead to a potential vulnerability if the behavior ever
changes so the code today overrides queries in both locations
independetly; and
* POST requests may send some …
> injectproxy: support queries via HTTP POST

- injectproxy/enforce.go
- injectproxy/enforce_test.go
- injectproxy/routes.go
- injectproxy/routes_test.go
- main.go
Before this commit, if the inject proxy is configured to replace label
foo and a query is encountered that has one or more label matchers for
the foo label, these matchers are silently replaced. E.g. a query like
`up{foo="default"}` would silently be altered to
`up{foo="replacement"}` and the query result returned.
With this change we return 400 instead.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
> return error if existing label matcher in query would change

- injectproxy/routes.go
- injectproxy/routes_test.go
Closes #55
Grafana always use POST when grafana alert query Prometheus ref: [grafana code](https://github.com/grafana/grafana/blob/main/pkg/tsdb/prometheus/prometheus.go#L89) , [prometheus client_golang code](https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/api.go#L1101)
Grafana 8.0 default use POST in Prometheus datasource. ref: [grafana#34599](https://github.com/grafana/grafana/pull/34599)
Current, `prom-label-proxy` cannot proxy POST method correctly.  
```
go run main.go  -label namespace -upstream http://127.0.0.1:9090 -insecure-listen-address :29192 -enable-label-apis -unsafe-passthrough-paths /api/v1/metadata,/api/v1/query_exemplars
```
main/master branch:
this PR fixed it, make `prom-label-proxy` proxy POST method correctly: 
hi @bwplotka  @s-urbaniak …
> Fully support POST: enforceLabel/matcher/labelAPI (#55)

- injectproxy/routes.go
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
Always parse form when we need to access the request body.
> always parse request post form

- README.md
- injectproxy/routes.go
- main.go
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> main.go: fix help text for --unsafe-passthrough-paths

- README.md
- injectproxy/routes.go
- injectproxy/silences.go
- injectproxy/silences_test.go
This PR addresses issue https://github.com/prometheus-community/prom-label-proxy/issues/89 by adding support for alerts/groups endpoint in alert manager
> adding support for alerts/groups endpoint of alert manager

- injectproxy/routes.go
- injectproxy/routes_test.go
Fixes  https://github.com/prometheus-community/prom-label-proxy/issues/51
Signed-off-by: Prashant Balachandran <pnair@redhat.com>
> fix: returning correct http status code in case of failures

- README.md
Hey there 👋 
First of all a big thanks to the community for building and maintaining an incredibly useful project.
[We built our own proxy](https://github.com/authzed/prom-authzed-proxy) based on prom-label-proxy that enables our users to query our internal Prometheus stack securely.
I think it'd be useful mention this in the README, because it uses this project as library, rather running it standalone and putting another proxy in front of it.
I'm also open to discussing where we found it difficult/annoying to use this project as a library and how we could improve that experience, if it's something the community is interested in.
> README: add authzed example

- injectproxy/routes.go
- injectproxy/routes_test.go
- injectproxy/rules_test.go
- injectproxy/silences.go
- injectproxy/silences_test.go
- injectproxy/utils.go
This PR changes the format of all error related http responses.
Instead send error as plain text, capsule the error into a json that follows normal prometheus API responses. https://prometheus.io/docs/prometheus/latest/querying/api/#http-api
The motivations of this change is to make errors visible in Grafana. Otherwise, errors are hard to debug, since the errors are not logged.
Before:
After:
> feat: Send errors in prometheus rest api format

- README.md
- injectproxy/routes.go
- injectproxy/routes_test.go
- injectproxy/rules_test.go
- main.go
This commit implements a -label-value flag which allows setting a static
label value when running prom-label-proxy. When this flag is set,
requests which contain a label value in the URL will get rejected
with a bad response status code.
> Allow setting static label value on start

- go.mod
- injectproxy/routes.go
Adds a `/metrics` endpoint to expose default Go metrics.
I initially went for adding this to the existent listener, but if needed be, we can create a dedicated listener for metrics only.
> feat: add /metrics endpoint

- .circleci/config.yml
This commit renames the occurences of `master` with `main` to allow
renaming the default branch for the project.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
> cleanup: rename default branch

- go.mod
- go.sum
- injectproxy/routes.go
- main.go
This commit adds an internal server to the prom-label-proxy that exposes
HTTP metrics about all of the routes registered with the
prom-label-proxy. The internal server also exposes pprof profiles. The
internal server is only activated if the --internal-listen-address flag
is provided.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
> instrumentation: add internal metrics server

- injectproxy/alerts_test.go
- injectproxy/routes.go
- injectproxy/routes_test.go
- injectproxy/rules.go
- injectproxy/rules_test.go
- injectproxy/silences.go
- injectproxy/silences_test.go
The package is deprecated since Go 1.16.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> chore: remove usage of io/ioutil

- README.md
- injectproxy/routes.go
- injectproxy/routes_test.go
- injectproxy/rules_test.go
- injectproxy/silences.go
- injectproxy/silences_test.go
- main.go
> Accept label value as regexp

- injectproxy/rules.go
I wanted to proceed a bit on trying to convert thanos to build with stringlabels and prom-label-proxy is used as a library there. This would fix this build error for me!
> chore: dont rely on slice labels

- injectproxy/rules.go
- injectproxy/rules_test.go
- injectproxy/testdata/rules_match_namespace_ns1.golden
- injectproxy/testdata/rules_match_namespace_ns2.golden
- injectproxy/testdata/rules_match_namespaces_ns1_and_ns2.golden
This commit adds the fields supported by newer Prometheus versions:
* /api/v1/rules
* `state` (for alerting rules only)
* `keepFiringFor` (for alerting rules only)
* `evaluationTime`
* `lastEvaluation`
* /api/v1/alerts
* `keepFiringSince`
> feat: update /api/v1/{rules,alerts} responses

- injectproxy/routes.go
- injectproxy/routes_test.go
- main.go
Currently, prom-label-proxy will accept multiple header values only if they correspond to separately-occurring header lines in the incoming HTTP request. Example request:
```
GET /api/v1/query?query=up HTTP/1.1
Host: localhost:9090
User-Agent: curl/7.68.0
X-Tenant: firsttenant
X-Tenant: secondtenant
Accept: */*
```
Attempting to pass multiple header values via list-style syntax as described in RFC 9110 (https://www.rfc-editor.org/rfc/rfc9110#name-field-lines-and-combined-fi), on the other hand, results in a single tenant value consisting of the entire comma-separated string. Example request:
```
GET /api/v1/query?query=up HTTP/1.1
Host: localhost:9090
User-Agent: curl/7.68.0
X-Tenant: firsttenant, secondtenant
Accept: */*
```
With the above sample request, the tenant label match …
> Adds the optional ability to split the tenant request header by comma

- README.md
- go.mod
- injectproxy/routes.go
- injectproxy/routes_test.go
- injectproxy/rules.go
- injectproxy/rules_test.go
PR #171 implemented support for regex label values but only for the query endpoints. This change adds support for all other Prometheus API endpoints.
FYI @sathieu. I remember that we discussed about the issue with the Alertmanager API endpoints but nothing about the non-query Prometheus endpoints. Let me know if the change looks sane.
> fix: support regex for non-query endpoints

- injectproxy/routes.go
- injectproxy/rules.go
- injectproxy/rules_test.go
With this change, the proxy returns a 400 status code instead of 502 when the incoming request contains multiple label values while the proxy is configured for regex matching (which allows only one label value).
> change: return 400 when the response can't be modified

- README.md
- injectproxy/enforce.go
- injectproxy/enforce_test.go
With this change, the proxy wouldn't necessary return an error if `-error-on-replace` is set and the incoming query has a label matcher overlapping with the enforced label.
For instance when the enforced label is `namespace="foo"`, the following expressions aren't rejected anymore:
- `up{namespace!="bar"}`
- `up{namespace=~"foo|bar"}`
- `up{namespace!~"bar"}`
The following expressions are rejected as before:
- `up{namespace=""}`
- `up{namespace="bar"}`
- `up{namespace=~"bar|fred"}`
- `up{namespace!~"foo"}`
> change: make `-error-on-replace` more cooperating

- README.md
- injectproxy/routes.go
- injectproxy/rules.go
- injectproxy/rules_test.go
- injectproxy/testdata/rules_with_active_alerts.golden
- main.go
This change adds a `-rules-with-active-alerts` CLI argument to return rules with active alerts matching the enforced label. The use case is for an admin to write general-purpose alerting rules which individual users can still retrieve from the API.
To avoid surprises ("why do I see this alert now?"), the feature needs to be explicitly enabled.
> feat: allow to return rules with matching active alerts
